package model;

public enum TakeActionCase {
    SUMMONED,
    REMOVE_FROM_MONSTERZONE,
    ATTACKED,
    FLIP_SUMMONED,
    SPECIAL_SUMMONED,
    DIED_BY_BEING_ATTACKED,
    ANY_MONSTER_PUT_IN_MONSTERZONE,
    PUT_IN_SPELLTRAPZONE,
    REMOVE_FROM_SPELLTRAPZONE,
    PUT_IN_FIELDZONE_FACE_UP,
    REMOVE_FROM_FIELDZONE_FACE_UP,
    ANY_SPELL_ACTIVATED
}
